CREATE TABLE `todo`.`task` (
  `ID` INT NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `STATUS` TINYINT(1) NULL,
  `ISDELETED` TINYINT(1) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `todo`.`task` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `todo`.`task` 
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NULL DEFAULT NULL ;

INSERT INTO `todo`.`task` (`ID`, `TITLE`, `STATUS`, `ISDELETED`) VALUES ('1', 'test', '0', '0');

ALTER TABLE `todo`.`task` 
CHANGE COLUMN `ISDELETED` `ISDELETED` TINYINT(1) NULL DEFAULT 0 ;

ALTER TABLE `todo`.`task` 
ADD COLUMN `TASKLIST_ID` INT(11) NULL AFTER `ISDELETED`,
ADD COLUMN `CREATED_DT` DATETIME NULL AFTER `TASKLIST_ID`,
ADD COLUMN `UPDATED_DT` DATETIME NULL AFTER `CREATED_DT`;

ALTER TABLE `todo`.`task` 
CHANGE COLUMN `CREATED_DT` `CREATED_DATE` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `UPDATED_DT` `UPDATED_DATE` DATETIME NULL DEFAULT NULL ;



--------------
CREATE TABLE `todo`.`tasklist` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(500) NULL,
  `ISDELETED` TINYINT(1) NULL DEFAULT 0,
  `CREATED_DATE` DATETIME NULL,
  `UPDATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `todo`.`tasklist` 
CHANGE COLUMN `NAME` `TITLE` VARCHAR(45) NOT NULL ;








